export const STRINGS = {
  chess: 'chess',
  checkers: 'checkers',
  whiteKingSrc: './resource/figures/white_king.png',
  blackKingSrc: './resource/figures/black_king.png',
  whiteCheckerSrc: './resource/figures/white_checker.png',
  blackCheckerSrc: './resource/figures/black_checker.png',
  empty: './resource/figures/empty.png',
  selected: 'selected',
  picked: 'picked',
  Queen: 'Q',
  queen: 'q',
  Damka: 'D',
  damka: 'd',
  king: 'king',
  rook: 'rook',
  pawn: 'pawn',
  checker: 'checker',
  wins: 'WINS',
}
